template_folder: template/
targer_folder: out/
static_resources: 
    - res/
templates:
    - style.css 
    - index.html
replace_dic:
    BREAKPOINT_CSS_FOOTER: 650px
    MARGIN_TOP_MAIN_DIV: 15vh
    WEBSITE_NAME: "Altair Bueno"
    WEBSITE_URL: "https://altair-bueno.github.io/"
    PROFILEPICTURE: "https://avatars.githubusercontent.com/u/67512202?v=4"
    STATIC_GENERATED: "Test string for comment"
    DESCRIPTION: "Altair's business card and contact info"
    AUTHOR_NAME: "Altair Bueno"
    GITHUB_TITLE: "Check Altair's projects on GitHub"
    GITHUB_URL: "https://github.com/Altair-Bueno"
    LINKEDIN_TITLE: "Find me in Linkedin"
    LINKEDIN_URL: "https://example.org"
    MAIL_TITLE: "Contact me"
    MAIL_URL: "mailto:business.altair.bueno@outlook.com"
    PROFILEPICTURE_TITLE: "Check the source code"
    PROFILEPICTURE_URL: "https://github.com/Altair-Bueno/altair-bueno.github.io"
    MAIN_BODY_CONTENT: |
        <h1>Lorem ipsum dolor sit amet</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
                incididunt ut labore et dolore magna aliqua. Elit scelerisque mauris pellentesque 
                pulvinar. Lorem donec massa sapien faucibus et molestie ac feugiat. A erat nam at 
                lectus. Nunc non blandit massa enim nec dui nunc. Diam vel quam elementum pulvinar.
            </p>
    TEMPLATE_CREATOR: |
        <div>
            Template made with ❤️ by <a class="footer_link" href="https://github.com/Altair-Bueno">Altair Bueno</a>
        </div>
