template_folder: template/
targer_folder: out/
static_resources: 
    - res/
templates:
    - style.css 
    - index.html
replace_dic:
    # Update to minimun screen size that looks good. Use 
    # 'Safari responsive design'
    BREAKPOINT_CSS_FOOTER: 650px
    # Margin between the main div and top of the webpage. Be carefull with
    # iPadOS' Safari
    MARGIN_TOP_MAIN_DIV: 15vh
    # webpage
    WEBSITE_NAME: "Altair Bueno"
    WEBSITE_URL: "https://altair-bueno.github.io/"
    PROFILEPICTURE: "https://avatars.githubusercontent.com/u/67512202?v=4"
    DESCRIPTION: "Altair's business card and contact info"
    AUTHOR_NAME: "Altair Bueno"
    # Github icon on div's  bottom left corner
    GITHUB_TITLE: "Check Altair's projects on GitHub"
    GITHUB_URL: "https://github.com/Altair-Bueno"
    GITHUB_ICON: res/github.svg
    # Linkedin icon on div's  bottom left corner
    LINKEDIN_TITLE: "Find me in Linkedin"
    LINKEDIN_URL: "https://example.org" # TODO placeholder link
    LINKEDIN_ICON: "res/linkedin.svg"
    # 'at' icon on div's bottom left corner
    MAIL_TITLE: "Contact me"
    MAIL_URL: "mailto:business.altair.bueno@outlook.com"
    MAIL_ICON: "res/mail.svg"
    # profile picture on the bottom right corner
    PROFILEPICTURE_TITLE: "Check the source code"
    PROFILEPICTURE_URL: "https://github.com/Altair-Bueno/altair-bueno.github.io"
    # main div content
    MAIN_BODY_CONTENT: |
        <h1>Lorem ipsum dolor sit amet</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
            incididunt ut labore et dolore magna aliqua. Elit scelerisque mauris pellentesque 
            pulvinar. Lorem donec massa sapien faucibus et molestie ac feugiat. A erat nam at 
            lectus. Nunc non blandit massa enim nec dui nunc. Diam vel quam elementum pulvinar.
        </p>
    # Other
    ACKNOWLEDGMENTS: |
        <div>@ icon made by <a class="footer_link" href="https://www.flaticon.com/authors/those-icons" title="Those Icons">Those Icons</a> from <a class="footer_link" href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
    TEMPLATE_CREATOR: |
        <div>
            Template made with ❤️ by <a class="footer_link" href="https://github.com/Altair-Bueno">Altair Bueno</a>
        </div>
    JAVA_SCRIPT: |
        <script>
            //window.location.replace("https://www.youtube.com/watch?v=dQw4w9WgXcQ");
        </script>

