name: "Build website"
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.x'
      - name: Compile templates
        run: python build.py

      - name: Delete existing docs/ content
        continue-on-error: true
        run: rm -rf docs/

      - name: Copy changed files to docs/ folder
        continue-on-error: true
        run: cp -u -R out/ docs/

      - name: Push back changes
        continue-on-error: true
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/
          git commit -am "Generated website"
          git push